[node]
detect-drivers = false
max-sessions = 3
override-max-sessions = true

[docker]
configs = [
    "selenium/standalone-firefox:latest", "{\"browserName\": \"firefox\"}",
    "selenium/standalone-chrome:latest", "{\"browserName\": \"chrome\"}",
    "selenium/standalone-edge:latest", "{\"browserName\": \"MicrosoftEdge\"}"
]

host-config-keys = ["Binds"]

# URL for connecting to the docker daemon
# Most simple approach, leave it as http://127.0.0.1:2375, and mount /var/run/docker.sock.
# 127.0.0.1 is used because internally the container uses socat when /var/run/docker.sock is mounted
# If var/run/docker.sock is not mounted:
# Windows: make sure Docker Desktop exposes the daemon via tcp, and use http://host.docker.internal:2375.
# macOS: install socat and run the following command, socat -4 TCP-LISTEN:2375,fork UNIX-CONNECT:/var/run/docker.sock,
# then use http://host.docker.internal:2375.
# Linux: varies from machine to machine, please mount /var/run/docker.sock. If this does not work, please create an issue.
url = "http://host.docker.internal:2375"
video-image = "selenium/video:latest"
