[node]
detect-drivers = false
max-sessions = 3
override-max-sessions = true

[docker]
configs = [
    "selenium/standalone-firefox:latest", "{\"browserName\": \"firefox\"}",
    "selenium/standalone-chrome:latest", "{\"browserName\": \"chrome\"}",
    "selenium/standalone-edge:latest", "{\"browserName\": \"MicrosoftEdge\"}"
]

# socat -4 TCP-LISTEN:2375,fork UNIX-CONNECT:/var/run/docker.sock
url = "http://host.docker.internal:2375"
video-image = "selenium/video:latest"
