name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  docker:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Start Selenium Grid
        run: grid/wait-for-grid.sh

      - name: Wait for Selenium Grid
        run: docker inspect --format='{{json .State.Health.Status}}' selenium-hub

      - name: Build with Maven
        run: mvn -B -q -DskipTests package --file pom.xml

      - name: Run parallel tests using TestNG
        run: mvn -B -q test -DsuiteXmlFile=src/test/resources/testng/parallel.xml

      - name: Stop containers
        if: always()
        run: docker-compose -f "grid/docker-compose.yml" down
